<?php
/**
 * Date: 30.11.15
 * Time: 23:26
 * @author Mariusz Filipkowski
 */

namespace Admin\Controller;




use Zend\Mvc\Controller\AbstractActionController;

class NewsController extends AbstractActionController{


    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

}