<?php
echo $this->doctype(); ?>
<html>
<head>
    <title>Testfight</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style_nowy.css'))
        ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css') ?>

    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/menu.js'))
        ->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.js')
        ->prependFile($this->basePath('js/jquery.js'))
    ?>

</head>
<body>
<div class="container">
    <div class="menu">
        <ul>
            <?php if($this->zfcUserIdentity()): ?>

                <li><a href="<?php echo $this->url('home'); ?>">Strona główna</a></li>
                <li><a href="#">Zawodnicy</a>
                    <ul>
                        <li><a href="<?php echo $this->url('zawodnik'); ?>">Lista</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url('taktyki',array('action'=>'lista')); ?>">Taktyka</a>
                </li>
                <li><a href="#">Federacja</a></li>
                <li><a href="#">Wiadomości</a></li>
                <li><a href="#">Czat</a></li>
                <li><a href="<?php echo $this->url('zfcuser/logout'); ?>" style="color: red">Wyloguj</a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->url('home'); ?>">Strona główna</a></li>
                <li><a href="<?php echo $this->url('zawodnik'); ?>">Zawodnik</a>
                    <ul>
                        <li><a href="<?php echo $this->url('zawodnik',array('action'=>'umiejetnosci')); ?>">Umiejętności</a></li>
                    </ul>
                </li>
                <li><a href="#">Trening</a>
                    <ul>
                        <li><a href="<?php echo $this->url('zawodnik'); ?>">Plan treningowy</a></li>
                    </ul>
                </li>
                <li><a href="#">Federacja</a></li>
                <li><a href="#">Wiadomości</a></li>
                <li><a href="#">Czat</a></li>
                <li><a href="<?php echo $this->url('zfcuser'); ?>">Zaloguj</a>
                    <ul>
                        <li><a href="<?php echo $this->url('zfcuser/register'); ?>">Rejestracja</a></li>
                    </ul>
                </li>
                <li><a href="#">Sklep</a></li>
            <?php endif; ?>
        </ul>
    </div>
    <div class="logo">
        <a href="<?php echo $this->url('home',array('action'=>'umiejetnosci')) ?>">
            <img src="<?php echo  $this->basePath('img/logo.png') ?>" alt="TESTFIGHT" style="margin-left: 50px;"/>
        </a>
    </div>
    <div class="content">
            <div class="left">
                <?php if($this->zfcUserIdentity()): ?>
                    <div class="avatar">
                        <img src="<?php echo $this->basePath('img/avatary/1.PNG') ?>" />
                    </div>
                      <br/>
                         <center>
                        Witaj, <a href="#">Mariusz Filipkowski</a>
                        </center>

                <?php endif; ?>
                <h2>Ostatnio zamieszczone</h2>
                <ul class="aktualnosci">
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="">Lorem ipsum dolor sit amet</a></li>
                </ul>

        </div>
        <div class="right">
            <?php

            if ($this->flashMessenger()->hasMessages()) {

                echo '<div class="alert alert-info">';

                $messages = $this->flashMessenger()->getMessages();
                foreach($messages as $message) {
                    echo $message;
                }

                echo '</div>';
            }
            ?>
            <?php echo $this->content; ?>
        </div>
    </div>
</div>
</body>
</html>
