<h1>Aktualności</h1>
<div class="post">
    <div class="dodano">
        Dodano: 7 Maja 2015r. <a href="">Kategoria</a>
    </div>
    <div class="miniaturka">
        <img src="<?php echo $this->basePath('img/aktualnosci/thumbnail.jpg') ?>" alt=""/>
    </div>
    <div class="info">
        Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść
    </div>
</div>
<div class="post">
    <div class="dodano">
        Dodano: 7 Maja 2015r. <a href="">Kategoria</a>
    </div>
    <div class="miniaturka">
        <img src="<?php echo $this->basePath('img/aktualnosci/thumbnail.jpg') ?>" alt=""/>
    </div>
    <div class="info">
        Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść
    </div>
</div>
<div class="post">
    <div class="dodano">
        Dodano: 7 Maja 2015r. <a href="">Kategoria</a>
    </div>
    <div class="miniaturka">
        <img src="<?php echo $this->basePath('img/aktualnosci/thumbnail.jpg') ?>" alt=""/>
    </div>
    <div class="info">
        Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść Treść
    </div>
</div>